spring.application.name=inventcontrol
spring.datasource.url=jdbc:postgresql://dpg-d6n1sms50q8c73assud0-a.oregon-postgres.render.com/inventcontrol_wusp
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

upload.path=uploads